blank_issues_enabled: false
contact_links:
  - name: Module Issue â•ğŸ›ğŸ”’
    url: https://aka.ms/AVM/Bicep/ModuleIssue
    about: Want to request a new Module feature or report a bug? Let us know!
